name: Kodi Addon Check (Custom)

on: [push, pull_request]

jobs:
  kodi-addon-checker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install kodi-addon-checker
      run: |
        pip install kodi-addon-checker
    
    - name: Run addon checker
      run: |
        kodi-addon-checker --branch matrix .
        